const AUDIT_ACTIONS = {
  // CRUD
  CREATE: "CREATE",
  READ: "READ",
  UPDATE: "UPDATE",
  DELETE: "DELETE",

  // Authentication
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REGISTER: "REGISTER",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",

  // Other
  STATUS_CHANGE: "STATUS_CHANGE",
  RESTORE: "RESTORE",
  EXPORT: "EXPORT",
  IMPORT: "IMPORT",
};

export default AUDIT_ACTIONS;