const MODULES = {
  AUTH: "AUTH",
  USER: "USER",

  BRANCH: "BRANCH",
  CATEGORY: "CATEGORY",
  UNIT: "UNIT",
  TAX: "TAX",
  PRODUCT: "PRODUCT",

  MENU: "MENU",
  ORDER: "ORDER",
  INVENTORY: "INVENTORY",
  CUSTOMER: "CUSTOMER",
  SUPPLIER: "SUPPLIER",

  PAYMENT: "PAYMENT",

  REPORT: "REPORT",
  DASHBOARD: "DASHBOARD",
  SETTINGS: "SETTINGS",
};

export default MODULES;