const MOVEMENT_TYPES = Object.freeze({
  PURCHASE: "PURCHASE",
  SALE: "SALE",
  RETURN: "RETURN",
  ADJUSTMENT: "ADJUSTMENT",
  TRANSFER_IN: "TRANSFER_IN",
  TRANSFER_OUT: "TRANSFER_OUT",
  WASTE: "WASTE",
  OPENING: "OPENING",
});

export default MOVEMENT_TYPES;