const PURCHASE_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  APPROVED: "APPROVED",
  RECEIVED: "RECEIVED",
  PARTIALLY_RECEIVED: "PARTIALLY_RECEIVED",
  CANCELLED: "CANCELLED",
});

export default PURCHASE_STATUS;