const REFERENCE_TYPES = Object.freeze({
  OPENING_STOCK: "OPENING_STOCK",

  PURCHASE: "PURCHASE",
  PURCHASE_RETURN: "PURCHASE_RETURN",

  SALE: "SALE",
  SALE_RETURN: "SALE_RETURN",

  STOCK_ADJUSTMENT: "STOCK_ADJUSTMENT",

  TRANSFER_IN: "TRANSFER_IN",
  TRANSFER_OUT: "TRANSFER_OUT",

  WASTE: "WASTE",
});

export default REFERENCE_TYPES;